config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  unauthenticated :user do
    root 'home#index', as: :unauthenticated_root
  end

  root 'groups#index'
  resources :groups, only: %i[index create destroy] do
    resources :transactions, only: %i[index create destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :group_transactions, dependent: :destroy
  has_many :payments, through: :group_transactions

  validates :name, presence: true
end

app/models/group_transaction.rb
class GroupTransaction < ApplicationRecord
  belongs_to :payment, dependent: :destroy
  belongs_to :group

  after_create :increase_total_amount
  after_destroy :decrease_total_amount

  private

  def increase_total_amount
    group.total_amount = 0 if group.total_amount.nil?
    group.total_amount += payment.amount
    group.update(total_amount: group.total_amount)
  end

  def decrease_total_amount
    group.total_amount -= payment.amount
    group.update(total_amount: group.total_amount)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :group_transactions
  has_many :groups, through: :group_transactions

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_float: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :payments, foreign_key: 'author_id'
  has_many :groups, foreign_key: 'author_id'

  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = current_user.groups
  end

  def create
    new_group = Group.new(groups_params)
    new_group.author = current_user

    respond_to do |format|
      format.html do
        if new_group.save
          flash[:success] = 'Your category has been created'
          redirect_back fallback_location: '/'
        end
      end
    end
  end

  def destroy
    if Group.find(params[:id]).destroy
      flash[:success] = 'Group item has been deleted'
    else
      flash[:alert] = 'Group item could not be deleted'
    end
    redirect_back fallback_location: '/'
  end

  private

  def groups_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @group = Group.includes(group_transactions: [:payment]).find(params[:group_id])
    @transactions = @group.group_transactions
  end

  def create
    groups = Group.find(transactions_params[:groups].reject(&:empty?))
    groups.each do |group|
      payment = Payment.new(name: transactions_params[:name], amount: transactions_params[:amount],
                            author: current_user)
      next unless payment.save
      gt = GroupTransaction.new(group:, payment:)
      gt.save
    end
    flash[:success] = 'Transaction created successfully'
    redirect_back fallback_location: '/'
  end

  def destroy
    if GroupTransaction.find_by(group_id: params[:group_id], payment_id: params[:id]).destroy
      flash[:success] = 'transaction item has been deleted'
    else
      flash[:alert] = 'transaction item could not be deleted'
    end
    redirect_back fallback_location: '/'
  end

  private

  def transactions_params
    params.require(:transaction).permit(:name, :amount, groups: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def icons
    {
      'Accounts' => 'bank2',
      'Crypto' => 'coin',
      'Savings' => 'safe-fill',
      'Shipping' => 'truck',
      'Fun' => 'balloon-fill',
      'Media' => 'boombox-fill',
      'Packages' => 'box2-fill',
      'Work' => 'building',
      'Shopping' => 'cart-fill'
    }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/groups/_add_category_form.html.erb
<%= form_with(model: category, url: groups_url, scope: :category, class: 'text-black') do |f| %>
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Add category</h5>
  </div>

  <div class="modal-body">
    <% if category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(category.errors.count, 'error') %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name, class: "form-label" %><br />
      <%= f.text_field :name, autofocus: true, class: "form-control", autocomplete: "name" %>
    </div>


    <div class="form-group">
      <div class="dropdown">
        <%= f.select :icon, [], {}, { class: "btn btn-secondary dropdown-toggle mt-3" } do %>
          <% icons.each do |category, icon| %>
            <option  value="<%= category %>"><%= category %></option>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="modal-footer justify-content-start">
    <% if category.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', category, method: :delete, class: 'text_danger', data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= f.submit class: 'btn btn-primary float-left' %>
  </div>
<% end %>

app/views/groups/index.html.erb
<article class="d-flex flex-column section">
  <nav class="navbar navbar-dak bg-primary">
    <div class="container-fluid text-center">
      <h2 class="navbar-brand mb-0 flex-grow-1 text-white fw-light">Most recent</h2>
    </div>
  </nav>

  <div class="container-fluid p-3 flex-grow-1">
    <% @groups.each do |group| %>
      <%= link_to group_transactions_url(group.id), class: 'group-card-link' do %>
        <div class="group-card d-flex gap-2 mb-3 p-1 bg-light">
            <i class="bi bi-<%= icons[group.icon] %> display-1 px-3 d-flex align-items-center"></i>
            <div class="d-flex flex-column flex-grow-1 justify-content-between pt-2">
              <h2 class="fs-5 fw-light text-gray"><%= group.name %></h2>
              <h2 class="fs-6 fw-light text-gray m-0"><%= group.created_at %></h2>
            </div>
              <div class="d-flex align-items-center gap-1">
                <% amount = group.total_amount %>
                <% if amount && amount > 0.0 %>
                  <span class="pt-2">total: <%= number_to_currency group.total_amount %></span>
                <% end %>
                <%= button_to group_path(group.id), method: :delete, class: "btn" do  %>
                  <i class="bi bi-trash fs-3 text-danger"></i>
                <% end %>
              </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="bg-secondary p-2 d-flex">
    <button type="button" class="btn btn-outline-light flex-grow-1" data-bs-toggle="modal" data-bs-target="#newCategoryModal">
      Add new category
    </button>
    <div class="modal fade" id="newCategoryModal" tabindex="-1" aria-labelledby="newCategoryModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <%= render partial: 'groups/add_category_form', locals: { category: Group.new } %>
        </div>
      </div>
    </div>
  </div>
</article>

app/views/home/index.html.erb
<section class="home d-flex flex-column">
  <div class="splash flex-grow-1">
  </div>
  <div class="d-flex flex-column bg-primary p-3 gap-3">
    <%= link_to 'Log in', new_user_session_path, class: 'btn btn-outline-light fs-3 fw-bold' %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-outline-light fs-3 fw-bold' %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="main">
      <div class="phone">
        <%= render partial: 'shared/navbar' %>
        <% if notice %>
          <div class="alert alert-success position-absolute top-0 start-0"><%= notice %></div>
        <% elsif alert %>
          <div class="alert alert-danger position-absolute top-0 start-0"><%= alert %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
    <% if current_user %>
      <h1 class="display-6 text-white">
        <% if controller_name == 'groups' %>
          Groups
        <% elsif controller_name == 'transactions' %>
          Transactions
        <% end %>
      </h1>
      <% if current_page?(root_path) %>
        <i class="bi bi-search fs-1 text-white"></i>
      <% elsif %>
 
      <% end %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0">
            <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary' %>
          <li>
          </li>
        </ul>
      </div>
    <% end %>
<% if current_user %>
<div id="navbar" class="relative bg-white" v-cloak>
  <div class="mx-auto max-w-7xl px-4 sm:px-6">
    <div class="flex items-center justify-between border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10">
      <div class="flex justify-start lg:w-0 lg:flex-1">
       <%= link_to root_path do %>
          <span class="sr-only">Your Company</span>
          <img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="">
        <% end %>
      </div>
      <div class="-my-2 -mr-2 md:hidden">
        <button 
           @click="menuHandler"
           type="button"
           class="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500"
           aria-expanded="false">
          <span class="sr-only">Open menu</span>
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
      <nav class="hidden space-x-10 md:flex">
        <a href="#" class="text-base font-medium text-gray-500 hover:text-gray-900">Report</a>
        <a href="#" class="text-base font-medium text-gray-500 hover:text-gray-900">Profile</a>
      </nav>
      <div class="hidden items-center justify-end md:flex md:flex-1 lg:w-0">
        <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'ml-8 inline-flex items-center justify-center whitespace-nowrap rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700' %>
      </div>
    </div>
  </div>
  <div v-show="menuShow" class="absolute inset-x-0 top-0 origin-top-right transform p-2 transition md:hidden">
    <div class="divide-y-2 divide-gray-50 rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
      <div class="px-5 pt-5 pb-6">
        <div class="flex items-center justify-between">
          <div>
            <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">
          </div>
          <div class="-mr-2">
            <button @click="menuHandler" type="button" class="inline-flex items-center justify-center rounded-md bg-white p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
              <span class="sr-only">Close menu</span>
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
        <div class="mt-6">
          <nav class="grid gap-y-8">
            <a href="#" class="-m-3 flex items-center rounded-md p-3 hover:bg-gray-50">
              <!-- Heroicon name: outline/chart-bar -->
              <svg class="h-6 w-6 flex-shrink-0 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z" />
              </svg>
              <span class="ml-3 text-base font-medium text-gray-900">Report</span>
            </a>

            <a href="#" class="-m-3 flex items-center rounded-md p-3 hover:bg-gray-50">
              <!-- Heroicon name: outline/cursor-arrow-rays -->
              <svg class="h-6 w-6 flex-shrink-0 text-indigo-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.042 21.672L13.684 16.6m0 0l-2.51 2.225.569-9.47 5.227 7.917-3.286-.672zM12 2.25V4.5m5.834.166l-1.591 1.591M20.25 10.5H18M7.757 14.743l-1.59 1.59M6 10.5H3.75m4.007-4.243l-1.59-1.59" />
              </svg>
              <span class="ml-3 text-base font-medium text-gray-900">Profile</span>
            </a>
          </nav>
        </div>
      </div>
      <div class="space-y-6 py-6 px-5">
        <div>
          <a href="#" class="flex w-full items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700">Sign up</a>
          <p class="mt-6 text-center text-base font-medium text-gray-500">
            Existing customer?
            <a href="#" class="text-indigo-600 hover:text-indigo-500">Sign in</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/transactions/_add_transaction_form.html.erb
<%= form_with(model: transaction, url: group_transactions_url(params[:group_id]), scope: :transaction, class: 'text-black') do |f| %>
  <div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Add transaction</h5>
  </div>

  <div class="modal-body">
    <% if transaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(transaction.errors.count, 'error') %> prohibited this transaction from being saved:</h2>

        <ul>
          <% transaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group mb-2">
      <%= f.label :name, class: "form-label" %><br />
      <%= f.text_field :name, autofocus: true, class: "form-control", autocomplete: "name" %>
    </div>

    <div class="form-group mb-2">
      <%= f.label :amount, class: "form-label" %><br />
      <%= f.text_field :amount, autofocus: true, class: "form-control", autocomplete: "amount" %>
    </div>

    <div class="form-group mb-2">
      <%= f.label :groups, class: "form-label" %><br />
      <div id="groupHelp" class="form-text">Select one or multiple(Crtl + click)</div>
      <%= f.select(:groups, options_from_collection_for_select(current_user.groups, :id, :name), {}, { :multiple => true, class: "form-control" } )%>
    </div>
  </div>

  <div class="modal-footer justify-content-start">
    <% if transaction.persisted? %>
      <div class="float-right">
        <%= link_to 'Destroy', transaction, method: :delete, class: 'text_danger', data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= f.submit class: 'btn btn-primary float-left' %>
  </div>
<% end %>

app/views/transactions/index.html.erb
<section class="transactions p-3 d-flex flex-column justify-content-between">
  <article class="transactions_card p-3 rounded">
    <header class="d-flex gap-3 align-items-center">
      <i class="bi bi-<%= icons[@group.icon] %>"></i>
      <h2 class="display-5"><%= @group.name %></h2>
    </header>
    <% @group.group_transactions.each do |group_transaction| %>
      <hr />
      <div class="d-flex justify-content-between">
        <div>
          <h3 class="display-6"><%= group_transaction.payment.name %></h3>
          <div class="d-flex align-items-center py-1 gap-2">
            <i class="bi bi-calendar fs-5"></i>
            <h6 class="m-0"><%= group_transaction.payment.created_at %></h6>
          </div>
        </div>  
        <div class="d-flex align-items-center gap-1">
          <span class="pt-2"><%= number_to_currency group_transaction.payment.amount %></span>
          <%= button_to group_transaction_path(@group.id, group_transaction.payment.id), method: :delete, class: "btn" do  %>
            <i class="bi bi-trash fs-3 text-danger"></i>
          <% end %>
        </div>
      </div>
    <% end %>
    <% amount = @group.total_amount %>
    <% if amount && amount > 0.0 %>
      <hr />
      <div class="d-flex justify-content-between align-items-center">
        <h2>TOTAL PAYMENT</h2>
        <span><%= number_to_currency @group.total_amount %></span>
      </div>
    <% end %>
  </article>
</section>

<div class="bg-secondary p-2 d-flex">
  <button type="button" class="btn btn-outline-light flex-grow-1" data-bs-toggle="modal" data-bs-target="#newCategoryModal">
    Add new transaction
  </button>
  <div class="modal fade" id="newCategoryModal" tabindex="-1" aria-labelledby="newCategoryModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= render partial: 'transactions/add_transaction_form', locals: { transaction: Payment.new } %>
      </div>
    </div>
  </div>
</div>